var config = {
  metroLine: {
    red: ["pink", "violet", "green", "yellow"],
    yellow: ["pink", "violet", "orange", "blue", "magenta", "rapid", "red"],
    blue: [
      "orange",
      "gray",
      "magenta",
      "pink",
      "green",
      "yellow",
      "violet",
      "aqua",
    ],
    orange: ["yellow", "blue"],
    green: ["red", "blue"],
    rapid: ["yellow"],
    violet: ["yellow", "blue", "pink", "magenta"],
    magenta: ["blue", "yellow", "violet"],
    pink: ["yellow", "red", "blue", "violet"],
    aqua: ["blue"],
    gray: ["blue"],
  },
  commonStation: {
    blue_orange: ["Dwarka Sector 21"],
    blue_gray: ["Dwarka"],
    blue_magenta: ["Janak Puri West", "Botanical Garden"],
    blue_pink: [
      "Rajouri Garden",
      "Mayur Vihar Phase-1",
      "Anand Vihar",
      "Karkarduma",
    ],
    blue_green: ["Kirti Nagar"],
    blue_yellow: ["Rajiv Chowk"],
    blue_violet: ["Mandi House"],
    blue_aqua: ["Noida Sector 52"],
    magenta_violet: ["Kalkaji Mandir"],
    magenta_yellow: ["Hauz Khas Enclave"],
    pink_yellow: ["Azadpur", "INA"],
    pink_red: ["Netaji Subash Place", "Welcome"],
    pink_violet: ["Lajpat Nagar"],
    green_red: ["Inderlok"],
    yellow_red: ["Kashmere Gate"],
    yellow_Violet: ["Kashmere Gate", "Central Secretariat"],
    yellow_rapid: ["Sikandarpur"],
  },
};

module.exports = config;
